version: 2.1

orbs:
  go: circleci/go@1.7
  codecov: codecov/codecov@5.3.0
  node: circleci/node@7.1.0

jobs:
  build-and-test:
    machine:
      image: ubuntu-2204:current
    resource_class: medium
    working_directory: ~/project

    steps:
      - checkout:
          path: ~/project

      - go/load-cache

      - go/mod-download

      - go/save-cache

      - run:
          name: Run linting
          command: |
            go install golang.org/x/lint/golint@latest
            golint -set_exit_status ./...

      - run:
          name: Run tests with coverage
          command: |
            go test -coverprofile=coverage.out -v ./...
            go tool cover -html=coverage.out -o coverage.html

      - store_artifacts:
          path: coverage.html
          destination: coverage-report

      - run:
          name: Build application
          command: |
            go build -o ./cmd/server

      - store_artifacts:
          path: app
          destination: backend-binary

      - codecov/upload:
          files: "coverage.out"
          slug: atomic-blend/backend
    
  build-mails:
    parameters:
      node_version:
        type: string
        default: "23.9"
    machine:
      image: ubuntu-2204:current
    resource_class: medium
    working_directory: ~/project

    steps:
      - checkout:
          path: ~/project
      
      - node/install:
          node-version: << parameters.node_version >>
      
      - node/install-packages:
          app-dir: ~/project/maizzle
          cache-path: ~/project/maizzle/node_modules
          override-ci-command: npm install
      
      - run:
          name: Build mails
          command: |
            cd ./maizzle
            npm run build


workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test
      - build-mails
