version: 2.1

orbs:
  go: circleci/go@1.7

jobs:
  build-and-test:
    docker:
      - image: cimg/go:1.23
    resource_class: docker-small
    working_directory: ~/project

    steps:
      - checkout:
          path: ~/project

      - setup_remote_docker:
          docker_layer_caching: true

      - go/load-cache

      - go/mod-download

      - go/save-cache

      - run:
          name: Run linting
          command: |
            go install golang.org/x/lint/golint@latest
            golint -set_exit_status ./...

      - run:
          name: Run tests with coverage
          command: |
            go test -coverprofile=coverage.out -v ./...
            go tool cover -html=coverage.out -o coverage.html

      - store_artifacts:
          path: coverage.html
          destination: coverage-report

      - run:
          name: Build application
          command: |
            go build -o ./cmd/server

      - store_artifacts:
          path: app
          destination: backend-binary

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test
