name: Build and Test

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          cache: true

      - name: Run linting
        run: |
          go install golang.org/x/lint/golint@latest
          golint -set_exit_status ./...

      - name: Run tests with coverage
        run: |
          go test -coverprofile=coverage.out -v ./...
          go tool cover -html=coverage.out -o coverage.html

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.html

      - name: Build application
        run: |
          go build -o ./cmd/server

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: backend-binary
          path: app

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.out
          fail_ci_if_error: false

  build-mails:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "23.9"
          cache: "npm"
          cache-dependency-path: "./maizzle/package-lock.json"

      - name: Install dependencies
        working-directory: ./maizzle
        run: npm install

      - name: Build mails
        working-directory: ./maizzle
        run: npm run build
